# yaml-language-server: $schema=./products.schema.json
- key: Iron_ore
  resource: true
- key: Iron_plate
  out: 1
  recipe:
    - key: Iron_ore
      in: 1
- key: Electronic_circuit
  out: 1
  recipe:
    - key: Copper_cable
      in: 3
    - key: Iron_plate
      in: 1
- key: Copper_cable
  out: 2
  recipe:
    - key: Copper_plate
      in: 1
- key: Copper_ore
  resource: true
- key: Copper_plate
  out: 1
  recipe:
    - key: Copper_ore
      in: 1
- key: Plastic_bar
  out: 2
  recipe:
    - key: Coal
      in: 1
    - key: Petroleum_gas
      in: 20
- key: Advanced_circuit
  out: 1
  recipe:
    - key: Copper_cable
      in: 4
    - key: Electronic_circuit
      in: 2
    - key: Plastic_bar
      in: 2
- key: Coal
  resource: true
- key: Petroleum_gas
  out: 45
  recipe:
    - key: Crude_oil
      in: 100
- key: Crude_oil
  resource: true
- key: Water
  resource: true
- key: Processing_unit
  out: 1
  recipe:
    - key: Advanced_circuit
      in: 2
    - key:  Electronic_circuit
      in: 20
    - key: Sulfuric_acid
      in: 5
- key: Sulfuric_acid
  out: 50
  recipe:
    - key: Iron_plate
      in: 1
    - key: Sulfur
      in: 5
- key: Sulfur
  out: 2
  recipe:
    - key: Petroleum_gas
      in: 30
    - key: Water
      in: 30
